#!/bin/sh
dch -b -v `curl --silent "https://api.github.com/repos/composer/composer/tags" | jq -r '.[0].name'`  --package composer "`curl -s https://api.github.com/repos/composer/composer/releases/latest | jq -r '.body'|grep '*'`"
